version: '3.8'

services:
  authservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_URLS=http://+:5000  
    ports:
      - "8080:80"    
      - "8443:443"   
      - "5009:5009"  
    networks:
      - app-network

  resumeanalyzermvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "8081:80"    
      - "8444:443"   
      - "5010:5010" 
    networks:
      - app-network

  resumeuploadservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "8082:80"    
      - "8445:443" 
      - "5011:5011" 
    networks:
      - app-network

  userservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "8083:80"    
      - "8446:443"   
      - "5012:5012"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
