version: '3.8'

services:
  authservice:
    build: ./AuthService
    ports:
      - "5001:5001"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=AuthServiceDB;User=ResumeAnalyzer;Password=prst1234
    depends_on:
      - db
    networks:
      - mynetwork

  userservice:
    build: ./UserService
    ports:
      - "5002:5002"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=UserServiceDB;User=ResumeAnalyzer;Password=prst1234
    depends_on:
      - db
    networks:
      - mynetwork

  resumeanalyzerservice:
    build: ./ResumeAnalyzerService
    ports:
      - "5003:5003"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ResumeAnalyzerDB;User=ResumeAnalyzer;Password=prst1234
    depends_on:
      - db
    networks:
      - mynetwork

  mvcfrontend:
    build: ./MVCFrontend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AuthService=http://authservice:5001
      - ConnectionStrings__UserService=http://userservice:5002
      - ConnectionStrings__ResumeAnalyzerService=http://resumeanalyzerservice:5003
    depends_on:
      - authservice
      - userservice
      - resumeanalyzerservice
    networks:
      - mynetwork

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: AuthServiceDB
      MYSQL_USER: ResumeAnalyzer
      MYSQL_PASSWORD: prst1234
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
