
services:
  authservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  resumeanalyzermvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:80"
      - "8444:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  resumeuploadservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:80"
      - "8445:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  userservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8083:80"
      - "8446:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
